import type { Metadata, Viewport } from "next";
import "./globals.css";
import NavBar from "../components/NavBar";
import { montserrat } from "./ui/fonts";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ToasterComponent } from "@/components/providers/toaster";
import Provider from "@/components/providers/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#171717",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={cn(
          `min-h-screen bg-light dark:bg-back text-color2 dark:text-light font-sans antialiased ${montserrat.variable}`
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          disableTransitionOnChange
        >
          <NavBar />
          <Provider>{children}</Provider>
          <ToasterComponent />
        </ThemeProvider>
      </body>
    </html>
  );
}
