import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/NavBar";
import { montserrat } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${montserrat.className} h-screen antialiased bg-color2 text-light`}>
        <NavBar />
        {children}
        </body>
    </html>
  );
}
